[package]
name = "keyboard-fireworks"
version = "0.1.0"
authors = ["droundy <roundyd@physics.oregonstate.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.3"
rand = "0.7.0"
